services:
    evirtua.payum.api.pagseguro:
        class: '%evirtua.payum.api.pagseguro.class%'
        arguments:
            - '%evirtua.payum.pagseguro.token%'
            - '%evirtua.payum.pagseguro.email%'
            - '%evirtua.payum.pagseguro.sandbox%'

    evirtua.payum.action.capture:
        class: '%evirtua.payum.action.capture.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: evirtua_payum.action, action: capture }

    evirtua.payum.action.status:
        class: '%evirtua.payum.action.status.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: evirtua_payum.action, action: status }

    evirtua.payum.action.notify:
        class: '%evirtua.payum.action.notify.class%'
        tags:
            - { name: evirtua_payum.action, action: notify }

    evirtua.payum.action.resolve_next_route:
        class: '%evirtua.payum.action.resolve_next_route.class%'
        tags:
            - { name: evirtua_payum.action, action: resolve_next_route }
